version: '3.8'
services:
  springboot-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${datasource}
      - SPRING_DATASOURCE_USERNAME=${postgres}
      - SPRING_DATASOURCE_PASSWORD=${password}
